version: "3.9"
services:
#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
  vendasService:
#    depends_on:
#      - "rabbitmq"
    ports:
      - "8081:8080"
    build: ./vendas-service
    image: "projarquistao/vendas-service:latest"
  estoqueService:
#    depends_on:
#      - "rabbitmq"
    ports:
      - "8082:8080"
    build: ./estoque-service
    image: "projarquistao/estoque-service:latest"
#  gateway:
#    ports:
#      - "8080:8080"
#    depends_on:
#      - "servCotacao"
#      - "servCambio"
#    build: ./Gateway
#    image: "gateway:latest"
